### ISSUE TITLE
502 error with traefik

### ISSUE THREAD

**Issue by letunglam** [ElGranLoky/unmark#1]
Anyone getting 502 when use this docker with traefik?

**Comment by ElGranLoky** [comment]
502 is normal if the app dont start fine, or missconfigure in traefik

Test before with a port mapping in docker, when works use traefik at the same time add these labels with the container:

```
traefik.http.routers.<nameofyourdockercontainer>.entrypoints = <nameoftraefikentrypoint>
traefik.http.routers.<nameofyourdockercontainer>.rule = Host(`<nameofyourdnsendpoint>`)
traefik.http.services.<nameofyourdockercontainer>.loadbalancer.server.port = 80
```

Good luck
